# Generated by Django 4.0 on 2022-01-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_eventbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingbooking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='start_date',
            field=models.DateField(),
        ),
    ]
