# Generated by Django 4.0 on 2022-01-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_trainingbooking_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.package')),
                ('yacht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.yacht')),
            ],
        ),
        migrations.RemoveField(
            model_name='yachtbooking',
            name='member',
        ),
        migrations.RemoveField(
            model_name='yachtbooking',
            name='yacht',
        ),
        migrations.DeleteModel(
            name='PackageBooking',
        ),
        migrations.DeleteModel(
            name='YachtBooking',
        ),
    ]
