# Generated by Django 4.0 on 2022-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking_remove_yachtbooking_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='persons',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
