# Generated by Django 4.0 on 2022-01-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_feedback_email_alter_feedback_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='last_name',
        ),
    ]
